console.log("Hello world!");
console.log("Hello world!");
console.log("Batch 2408B2");
console.log("Batch 2408B2");
console.log("Batch 2408B2");
document.write("Aptech Learning");
document.write("Aptech Learning");
document.write("Aptech Learning");
var naam = "Bilal";
// naam = 123;
console.log(naam);
console.log(naam);
console.log(naam);
var data = "Any Type Of Data";
data = 123;
console.log(data);
