// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxQp9DTwk6TL_oACd5eHCqLGtwLwFTeVw',
    appId: '1:1007593972465:web:06d008dac4dd733adf7f50',
    messagingSenderId: '1007593972465',
    projectId: 'mobileappflutter-cc308',
    authDomain: 'mobileappflutter-cc308.firebaseapp.com',
    storageBucket: 'mobileappflutter-cc308.firebasestorage.app',
    measurementId: 'G-M5D02YHTHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyAE8c0YIUEsB8PJMJgiaXvOWkjjhV9Og',
    appId: '1:1007593972465:android:c8a82f66866b9ca4df7f50',
    messagingSenderId: '1007593972465',
    projectId: 'mobileappflutter-cc308',
    storageBucket: 'mobileappflutter-cc308.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMPDoEdt3WuI8oCtHo6Uxa9fCIgD7vi-Y',
    appId: '1:1007593972465:ios:0b209a3f74d77a54df7f50',
    messagingSenderId: '1007593972465',
    projectId: 'mobileappflutter-cc308',
    storageBucket: 'mobileappflutter-cc308.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMPDoEdt3WuI8oCtHo6Uxa9fCIgD7vi-Y',
    appId: '1:1007593972465:ios:0b209a3f74d77a54df7f50',
    messagingSenderId: '1007593972465',
    projectId: 'mobileappflutter-cc308',
    storageBucket: 'mobileappflutter-cc308.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxQp9DTwk6TL_oACd5eHCqLGtwLwFTeVw',
    appId: '1:1007593972465:web:190a2cf7b9d651a8df7f50',
    messagingSenderId: '1007593972465',
    projectId: 'mobileappflutter-cc308',
    authDomain: 'mobileappflutter-cc308.firebaseapp.com',
    storageBucket: 'mobileappflutter-cc308.firebasestorage.app',
    measurementId: 'G-K4C1Y8ELM4',
  );
}
